export const ADD_BOOK_TITLES = 'ADD_BOOK_TITLES';
export const RESET_BOOK_TITLES = 'RESET_BOOK_TITLES';
export const TRUE_ISSUGGESTIONCHOSEN = 'TRUE_ISSUGGESTIONCHOSEN';
export const FALSE_ISSUGGESTIONCHOSEN = 'FALSE_ISSUGGESTIONCHOSEN';
export const ADD_BOOKS = 'ADD_BOOKS';
// export const SET_INPUT_VALUE = 'SET_INPUT_VALUE';

